CREATE TABLE users (
    username VARCHAR(25) PRIMARY KEY,
    password TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
        CHECK (position('@' IN email) > 1),
    is_admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE topics (
    title TEXT NOT NULL PRIMARY KEY,
    date_created TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(25) NOT NULL REFERENCES users,
    area_zone TEXT NOT NULL
);

CREATE TABLE posts (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    votes INTEGER NOT NULL DEFAULT 0,
    date_created TIMESTAMP without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(25) NOT NULL REFERENCES users
        ON DELETE CASCADE,
    topic_title TEXT NOT NULL REFERENCES topics ON DELETE CASCADE
);

CREATE TABLE comments (
    id SERIAL PRIMARY KEY,
    post_id INTEGER REFERENCES posts ON DELETE CASCADE,
    content TEXT NOT NULL,
    votes INTEGER NOT NULL DEFAULT 0,
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(25) NOT NULL REFERENCES users
        ON DELETE CASCADE
);

CREATE TABLE comment_responses (
    id SERIAL PRIMARY KEY,
    comment_id INTEGER REFERENCES posts ON DELETE CASCADE,
    content TEXT NOT NULL,
    votes INTEGER NOT NULL DEFAULT 0,
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(25) NOT NULL REFERENCES users
        ON DELETE CASCADE
);
